@ECHO OFF

ECHO START Half-open TCP Connection Test Full Environment
PAUSE

START LDM\MASTER\HOT.exe
START LDM\SLAVE1\HOT.exe
START LDM\SLAVE2\HOT.exe
START LDM\SLAVE3\HOT.exe
START LDM\SLAVE4\HOT.exe
START LDM\TARGET\HOT.exe
